DROP TABLE IF EXISTS AOM_ACTIE_TCMG ;
CREATE TABLE AOM_ACTIE_TCMG (
    Actie_cd varchar (3),
    Actie_oms varchar (60),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    timestamp varchar (8)
);

DROP TABLE IF EXISTS AOM_TRA_ACTIE_TCMG ;
CREATE TABLE AOM_TRA_ACTIE_TCMG (
    Actie_cd varchar (3),
    Bgt_cd varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Tra_cd varchar (3)
);

DROP TABLE IF EXISTS AOM_TRANSACTIETYPE_TCMG ;
CREATE TABLE AOM_TRANSACTIETYPE_TCMG (
    Beleidsadministratie_jn varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Geldstroom_jn varchar (1),
    Mdw_mandaat_jn varchar (1),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Tra_cd varchar (3),
    Tra_oms varchar (50),
    Tra_stop varchar (1)
);

DROP TABLE IF EXISTS BTM_BETALING_TCMG ;
CREATE TABLE BTM_BETALING_TCMG (
    Rel_id integer,
    Tra_id integer,
    Reg_cd varchar (20),
    Dos_cd varchar (10),
    Bedrag integer,
    Bedrag_nlg integer,
    Omschrijving varchar (64),
    Naam_begunstigde varchar (60),
    Betalingskenmerk varchar (5),
    Plaats varchar (80),
    Aanleverdatum timestamp,
    Status varchar (1),
    Betaalrun_id integer,
    Bron varchar (4),
    Invoerdatum timestamp,
    Mdw_id integer,
    Betaling_id integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Iban varchar (34),
    Bic varchar (11),
    Beg_bic varchar (11),
    Beg_iban varchar (34),
    Sepa_betaling_indicatie varchar (1),
    Parkeer_valutadatum timestamp,
    Betalingsverzoeknummer varchar (40),
    Betaal_datum timestamp,
    On_hold_jn varchar (1),
    Sepa_xsd_bevinding varchar (2048)
);

DROP TABLE IF EXISTS BTM_HIST_BETALING_TCMG ;
CREATE TABLE BTM_HIST_BETALING_TCMG (
    Rel_id integer,
    Tra_id integer,
    Reg_cd varchar (20),
    Dos_cd varchar (20),
    Bedrag integer,
    Bedrag_nlg integer,
    Omschrijving varchar (64),
    Naam_begunstigde varchar (60),
    Plaats varchar (30),
    Rekeningnummer integer,
    Senterrekening integer,
    Aanleverdatum timestamp,
    Betaalrun_id integer,
    Bron varchar (4),
    Valutadatum timestamp,
    Invoerdatum timestamp,
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Mdw_id integer,
    Betalingskenmerk varchar (5),
    Iban varchar (34),
    Bic varchar (11),
    Beg_bic varchar (11),
    Beg_iban varchar (34),
    Sepa_betaling_indicatie varchar (1),
    Parkeer_valutadatum timestamp,
    Betalingsverzoeknummer varchar (40)
);

DROP TABLE IF EXISTS COR_BERICHT_TCMG ;
CREATE TABLE COR_BERICHT_TCMG (
    Cor_id integer,
    Ed_bericht_id integer,
    Afzender_id integer,
    Ontvanger_id integer,
    Inkomend varchar (1),
    Handtekening_ok varchar (1),
    Ondertekenaar_id integer,
    Onderwerp varchar (256),
    Inhoud varchar (2048),
    Certserienummer varchar (50),
    Batch_status integer,
    Status_overzetten_bericht integer,
    Ingezien varchar (1),
    Plattetekst varchar (8000),
    Status_verzending varchar (1),
    Archief_cor_id integer,
    Bron varchar (10),
    Org_cor_id integer
);

DROP TABLE IF EXISTS COR_COR_PARAAF_TCMG ;
CREATE TABLE COR_COR_PARAAF_TCMG (
    Acc_id integer,
    Acc_rol_cd varchar (3),
    Acc_vaste_paraaf_jn varchar (1),
    Afgehandeld_JN varchar (1),
    Akkoord varchar (1),
    Cor_bedrag integer,
    Cor_id integer,
    Creatie_dat timestamp,
    Creatie_ok_JN varchar (1),
    Creatie_user varchar (30),
    Datum_Akkoord timestamp,
    Email_JN varchar (1),
    Mandaat_ok_JN varchar (1),
    Max_bedrag integer,
    Mdw_id integer,
    Mdw_id_doorvoerder integer,
    Mdw_id_oorspronkelijk integer,
    Mdw_mandaat_JN varchar (1),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Rol_cd varchar (3),
    Rol_ok_JN varchar (1),
    Rol_volg_cd varchar (1),
    Toelichting varchar (2000),
    Type_paraaf varchar (1),
    Vaste_paraaf varchar (1),
    Volgorde integer
);

DROP TABLE IF EXISTS COR_COR_SRT_TCMG ;
CREATE TABLE COR_COR_SRT_TCMG (
    Cst_cd varchar (8),
    Cst_oms varchar (60),
    Cst_template varchar (100),
    Regeling varchar (1),
    Thema varchar (1),
    Dossier varchar (1),
    Project varchar (1),
    Organisatie varchar (1),
    Bezoek varchar (1),
    Transactie varchar (1),
    Uitgaand_inkomend varchar (1),
    Juridisch varchar (1),
    Stempel_sj varchar (1),
    Bob_brief varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Vorderingbeheer varchar (1),
    Externe_naam varchar (65),
    Correctie_jn varchar (1),
    Intern_jn varchar (1)
);

DROP TABLE IF EXISTS COR_CORRESPONDENTIE_HIST_TCMG ;
CREATE TABLE COR_CORRESPONDENTIE_HIST_TCMG (
    Cor_id integer,
    Volg_nr integer,
    Correctie_code varchar (5),
    Oude_verzenddatum timestamp,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30)
);

DROP TABLE IF EXISTS COR_CORRESPONDENTIE_TCMG ;
CREATE TABLE COR_CORRESPONDENTIE_TCMG (
    Actie_datum timestamp,
    Afgedrukt_JN varchar (1),
    Afgehandeld varchar (1),
    Archiveren varchar (1),
    Bas_da_melding varchar (2048),
    Behandelingsronde integer,
    Bezoeknr integer,
    Bos_status varchar (2),
    Cbi_id integer,
    Certhoud_contpers_intern integer,
    Cor_bericht varchar (1),
    Cor_id integer,
    Cor_id_van integer,
    Cor_volgnr_ids integer,
    Crd_id integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Cst_cd varchar (8),
    Datum timestamp,
    Datum_ok varchar (1),
    Datum_stempel_sj timestamp,
    Digitaal_archiveren varchar (3),
    Doc_directory varchar (100),
    Doc_naam varchar (40),
    Dos_id integer,
    Dossiergroep_cor_id integer,
    Email_JN varchar (1),
    Genereer_JN varchar (1),
    Html varchar (2048),
    Ids_id integer,
    Indieningsdatum timestamp,
    Ingetrokken varchar (1),
    Jz_id integer,
    Kenmerk varchar (40),
    Lijst_cd varchar (20),
    Mandaat_rol_cd varchar (3),
    Mdw_cd_email varchar (30),
    Mdw_id_contpers_intern integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    naam_organisatie varchar (625),
    Ok_JN varchar (1),
    Omschrijving varchar (2000),
    Open_brief varchar (1),
    Org_id integer,
    Pcs_id integer,
    Plandatum timestamp,
    Prioriteit integer,
    Reg_id integer,
    Rel_id integer,
    Rol_cd varchar (3),
    Run_id integer,
    Select_export varchar (1),
    Senterkenmerk varchar (40),
    Text_inhoud varchar (2048),
    Vernieuw_paraaf varchar (1),
    Verzenddatum timestamp,
    Verzonden_elektronisch_JN varchar (1),
    Verzonden_per_post_JN varchar (1),
    Vst_volgnr integer,
    Wordbrief_akkoord varchar (1),
    Xml_inhoud varchar (2048),
    Xsl varchar (2048)
);

DROP TABLE IF EXISTS COR_CST_SET_CST_TCMG ;
CREATE TABLE COR_CST_SET_CST_TCMG (
    Reg_id integer,
    Cst_cd varchar (8),
    Cst_cd_2 varchar (8),
    Verzenddatum_jn varchar (1),
    Afgehandeld_jn varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Genereer_jn varchar (1)
);

DROP TABLE IF EXISTS COR_PARAAF_TCMG ;
CREATE TABLE COR_PARAAF_TCMG (
    Reg_id integer,
    Cst_cd varchar (8),
    Type_paraaf varchar (1),
    Rol_cd varchar (3),
    Mdw_rol_niveau varchar (3),
    Volgorde integer,
    Vaste_paraaf_jn varchar (1),
    Rol_volg_cd varchar (1)
);

DROP TABLE IF EXISTS COR_REACTIE_BIJ_COR_SRT_TCMG ;
CREATE TABLE COR_REACTIE_BIJ_COR_SRT_TCMG (
    Cluster_nr integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Cst_cd varchar (8),
    Mdw_id varchar (12),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Per_cluster varchar (1),
    Prg_id integer,
    Prioriteit integer,
    Reactie_cd varchar (3),
    Reg_id integer,
    Rol_cd varchar (3),
    Sts_cd varchar (3),
    Termijn integer,
    Termijn_weken integer
);

DROP TABLE IF EXISTS COR_REGLSPEC_COR_TCMG ;
CREATE TABLE COR_REGLSPEC_COR_TCMG (
    Bos_bezorging varchar (1),
    Crea_back varchar (1),
    Create_merge_jn varchar (1),
    Create_merge_single varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Cst_cd varchar (8),
    Doc_template varchar (150),
    Externe_naam varchar (65),
    Geblokkeerd_jn varchar (1),
    Ic_controle varchar (1),
    Job varchar (30),
    Lijst_cd varchar (20),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Prf_cd varchar (8),
    Print_jn varchar (1),
    Prioriteit integer,
    Reg_id integer,
    Verzenddatum_vullen varchar (1)
);

DROP TABLE IF EXISTS COR_TRANSACTIEGROEP_BIJ_BRF_TCMG ;
CREATE TABLE COR_TRANSACTIEGROEP_BIJ_BRF_TCMG (
    Cor_id integer,
    Tra_id integer,
    Dos_id integer,
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp
);

DROP TABLE IF EXISTS DAM_CONT_BIJ_DLN_COM_ADR_TCMG ;
CREATE TABLE DAM_CONT_BIJ_DLN_COM_ADR_TCMG (
    creatie_dat timestamp,
    Creatie_user varchar (30),
    Dcs_id integer,
    Dos_id integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Per_id integer,
    Rav_id integer,
    Rca_id integer,
    Rel_id integer,
    Rol_cd varchar (3),
    Rol_cd_van varchar (3),
    Vst_volgnr integer
);

DROP TABLE IF EXISTS DAM_CONTACT_BIJ_DEELNAME_TCMG ;
CREATE TABLE DAM_CONTACT_BIJ_DEELNAME_TCMG (
    Certhoud_id integer,
    Correspondent varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Dos_id integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Per_id integer,
    Rechten_id varchar (1),
    Rel_id integer,
    Rol_cd varchar (3),
    Rol_cd_van varchar (3),
    Vst_volgnr integer
);

DROP TABLE IF EXISTS DAM_DECLARATIE_TCMG ;
CREATE TABLE DAM_DECLARATIE_TCMG (
    Adviesaangevraagd integer,
    Adviesaantaluren integer,
    Advieshandtoegekend integer,
    Adviesrente integer,
    Adviesrentedatum timestamp,
    Adviestoegekend integer,
    Besluit_cor_id integer,
    Cor_id integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Datumberekening timestamp,
    Dos_id integer,
    Herstel varchar (1),
    Inboedeltuinaangevraagd integer,
    Inboedeltuinhandtoegekend integer,
    Inboedeltuinrente integer,
    inboedeltuinrentedatum timestamp,
    Inboedeltuintoegekend integer,
    Inkomstendervingaangevraagd integer,
    Inkomstendervinghandtoegekend integer,
    Inkomstendervingrente integer,
    Inkomstendervingrentedatum timestamp,
    Inkomstendervingtoegekend integer,
    Juridischaangevraagd integer,
    Juridischaantaluren integer,
    Juridischhandtoegekend integer,
    Juridischrente integer,
    Juridischrentedatum timestamp,
    Juridischtarief integer,
    Juridischtoegekend integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Notitie varchar (2048),
    Oorzaak varchar (2048),
    Opslagaangevraagd integer,
    Opslagaantalweken integer,
    Opslaghandtoegekend integer,
    opslagrente integer,
    Opslagrentedatum timestamp,
    Opslagtoegekend integer,
    Overlastaangevraagd integer,
    Overlasthandtoegekend integer,
    Overlastrente integer,
    Overlasttoegekend integer,
    Overlastvergoeding varchar (1),
    Overnachtenaangevraagd integer,
    Overnachtenaantalnachten integer,
    Overnachtenaantalpersonen varchar (20),
    Overnachtenhandtoegekend integer,
    Overnachtenrente integer,
    Overnachtenrentedatum timestamp,
    Overnachtentoegekend integer,
    Reisaangevraagd integer,
    Reisaantalkm integer,
    Reishandtoegekend integer,
    Reisov integer,
    Reisrente integer,
    Reisrentedatum timestamp,
    Reistoegekend integer,
    Schoonmaakaangevraagd integer,
    Schoonmaakhandtoegekend integer,
    Schoonmaakrente integer,
    Schoonmaaktoegekend integer,
    Schoonmaakvergoeding varchar (1),
    Thuisblijfherstelaangevraagd integer,
    Thuisblijfherstelaantaldagdeel integer,
    Thuisblijfherstelhandtoegekend integer,
    Thuisblijfherstelrente integer,
    Thuisblijfhersteltoegekend integer,
    Thuisblijfherstelvergoeding varchar (1),
    Thuisblijfopnameaangevraagd integer,
    Thuisblijfopnamehandtoegekend integer,
    Thuisblijfopnamerente integer,
    Thuisblijfopnametoegekend integer,
    Thuisblijfopnamevergoeding varchar (1),
    Totaalrente integer,
    Totaaltoegekend integer,
    Verhuisaangevraagd integer,
    Verhuishandtoegekend integer,
    Verhuisrente integer,
    Verhuisrentedatum timestamp,
    Verhuistoegekend integer,
    Zorgaangevraagd integer,
    Zorghandtoegekend integer,
    Zorgrente integer,
    Zorgrentedatum timestamp,
    Zorgtoegekend integer
);

DROP TABLE IF EXISTS DAM_DEELNAME_ADRES_TCMG ;
CREATE TABLE DAM_DEELNAME_ADRES_TCMG (
    Adressoort varchar (3),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Dda_id integer,
    Dos_id integer,
    Kkr_afwijkend varchar (1),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Rae_id integer,
    Ras_id integer,
    Rel_id integer,
    Rol_cd varchar (3),
    Vst_volgnr integer
);

DROP TABLE IF EXISTS DAM_DEELNAME_COM_ADRES_TCMG ;
CREATE TABLE DAM_DEELNAME_COM_ADRES_TCMG (
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Dda_id integer,
    Dos_id integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Rae_id integer,
    Rca_id integer,
    Rel_id integer,
    Rol_cd varchar (3),
    Vst_volgnr integer
);

DROP TABLE IF EXISTS DAM_DEELNAME_TCMG ;
CREATE TABLE DAM_DEELNAME_TCMG (
    Afwijking_cd varchar (6),
    Bic varchar (11),
    Bic_cd varchar (8),
    Contract_cd varchar (30),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Dam_project_deelname varchar (1),
    Deelnamenaam varchar (625),
    Dos_id integer,
    Ed_deelnemer_id integer,
    Edeelnemer_id integer,
    Einddatum timestamp,
    Elektronisch_corresponderen_JN varchar (1),
    Fisc_eenheid varchar (1),
    Geclaimd integer,
    Geclaimd_NLG integer,
    Gedeclareerd integer,
    Gedeclareerd_NLG integer,
    Gerealiseerd integer,
    Gerealiseerd_NLG integer,
    Geschoond integer,
    Geschoond_NLG integer,
    IBAN varchar (34),
    Ingediend integer,
    Ingediend_NLG integer,
    Kkr_statutair varchar (1),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Niet_sepa_betalen varchar (1),
    Org_id integer,
    Org_naam varchar (625),
    Pom_ranking varchar (1),
    Rel_id integer,
    Rel_id_rekening integer,
    Rol_cd varchar (3),
    Startdatum timestamp,
    Totaal_decl_deelname integer,
    Totaal_uitb_deelname integer,
    Verklaring_gewenst_JN varchar (1),
    Vst_volgnr integer
);

DROP TABLE IF EXISTS DAM_DOS_BUDGETREGEL_TCMG ;
CREATE TABLE DAM_DOS_BUDGETREGEL_TCMG (
    Dos_id integer,
    Tra_id integer,
    Volgnummer integer,
    Ovk_nr varchar (20),
    Rpt_nr integer,
    Bgt_cd varchar (1),
    Verleend integer,
    Ingetrokken integer,
    Gedeclareerd integer,
    Betaald integer,
    Vastgesteld integer,
    Openstaand integer,
    Opeisbaar integer,
    Def_verleend integer,
    Def_ingetrokken integer,
    Def_gedeclareerd integer,
    Def_openstaand integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Rpe_datum_van timestamp,
    Neg_einddeclaratie integer,
    Prg_id integer,
    Reg_id integer,
    Reg_nr integer,
    Afl_neg_einddeclaratie integer,
    Def_neg_einddeclaratie integer,
    Cvk_id integer,
    Vpl_volgnummer integer,
    Rpt_nr_oud varchar (20),
    Per_Deelnemer varchar (1)
);

DROP TABLE IF EXISTS DAM_DOSSIER_IN_GROEP_TCMG ;
CREATE TABLE DAM_DOSSIER_IN_GROEP_TCMG (
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Ddg_id integer,
    Dds_id integer,
    Dos_id integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30)
);

DROP TABLE IF EXISTS DAM_DOSSIER_NOTITIE_TCMG ;
CREATE TABLE DAM_DOSSIER_NOTITIE_TCMG (
    Afgehandeld varchar (1),
    Bezoeknr integer,
    Cor_id_no integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Dos_id integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Notitie varchar (2048),
    Notitietype_naam varchar (50),
    Rel_id integer
);

DROP TABLE IF EXISTS DAM_DOSSIER_TCMG ;
CREATE TABLE DAM_DOSSIER_TCMG (
    Aangevraagd_bedrag integer,
    Aantal_dagenopschorting integer,
    Aantal_ICT_projecten integer,
    Aantal_SO_projecten integer,
    Aantal_SO_werknemers integer,
    Aantal_SO_zlf integer,
    Aanvang_dat timestamp,
    Aanvraag_volgnr integer,
    Aanvraagsoort varchar (10),
    Acceptatie_sts varchar (1),
    Afdrachtsvermindering varchar (1),
    Afhandeldatum timestamp,
    Afhandelwijze varchar (512),
    Afl_neg_einddeclaratie integer,
    Akkoord_verlenen varchar (1),
    aut_verwerkt_imp varchar (1),
    Auth_id_indiener integer,
    Auth_id_ondertekenaar integer,
    Auth_prg_id integer,
    BAS_advies varchar (512),
    Batchstatuscert varchar (1),
    Batchstatusref varchar (1),
    Batchstatusstat varchar (1),
    Behandelingsronde integer,
    Beoordelingswijze varchar (4),
    Berekende_rente integer,
    Beslissing_cd varchar (2),
    Checksum integer,
    Classificatie varchar (10),
    Cluster_nr integer,
    Controle_activiteit varchar (1),
    Commercieel_perspectief varchar (1),
    Contractjaar integer,
    Conversiedossier varchar (1),
    Correspondentie_via_email varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Jaardossier_WBSO varchar (1),
    Datum_in timestamp,
    Datum_renteberekening timestamp,
    Datum_status timestamp,
    Volgnr_diskette integer,
    Volgnr_diskette_na_import integer,
    Dos_cd varchar (20),
    Dos_id integer,
    Dos_id_aanvulling integer,
    Dosprio integer,
    ED_Aanvraag_id integer,
    Eerste_jr_aflossing integer,
    Eind_dat timestamp,
    Eindmaand integer,
    Extern_aanvraag_id integer,
    Extern_dossier_id integer,
    Extrene_bron_cd varchar (10),
    Gecommitteerd_zegge varchar (100),
    Gem_uurloon integer,
    Hand_bewerkt_imp varchar (1),
    Handtekening_ok varchar (1),
    Hoofd_dos_id integer,
    Id_van_de_doos integer,
    Id_van_de_doos_na_de_import integer,
    Importlijst varchar (240),
    Indienings_dat timestamp,
    Indienings_tijd timestamp,
    Indienkanaal varchar (1),
    Ingezien varchar (1),
    Inkoopcat_cd varchar (6),
    Inleen_binnen_Fiscale_eenheid varchar (1),
    Meldingnummer_IRWA varchar (30),
    Jaar integer,
    Jaardossier_bron_dos_id integer,
    Jaardossier_dos_id integer,
    Korte_titel varchar (25),
    Krat_nr integer,
    Laatste_jr_aflossing integer,
    Laatste_pcs_id integer,
    Landnaam varchar (60),
    LB_nummer_komt_overeen varchar (1),
    Machtiging_JN varchar (1),
    Mdw_cd varchar (30),
    Mentorterugkoppeling varchar (1),
    Mutatie_dat timestamp,
    Mutatie_dat_vst timestamp,
    Mutatie_user varchar (30),
    Mutatie_user_vst varchar (30),
    Naar_batchrun integer,
    Neg_einddeclaratie integer,
    Notities varchar (2048),
    Octrooien integer,
    Offertebedrag integer,
    Cerhoud_id_Ondertekenaar integer,
    Ontvangstdatum timestamp,
    Oorspr_einddatum timestamp,
    Overige_subsidie varchar (1),
    Opdrachtvorm_cd varchar (3),
    Perc_verrekenen integer,
    Periode_nr integer,
    Prioriteit integer,
    Prioriteitsdatum timestamp,
    Projectomschrijving varchar (2048),
    Ranking integer,
    RDA_Afhandeling_forfaitair varchar (1),
    RDA_aangevraagd varchar (1),
    Referentie varchar (10),
    Reg_id integer,
    Reg_nr integer,
    Rel_id_Aanvrager integer,
    Rente_perc integer,
    Samenwerkingsverband1 varchar (1),
    Samenwerkingsverband2 varchar (1),
    SO_loon integer,
    Begrote_SO_loonsom integer,
    SO_uren integer,
    Startmaand integer,
    Statuscode varchar (3),
    Status_cert varchar (1),
    Status_oud varchar (1),
    status_SO_uurloon varchar (1),
    Status_TT varchar (3),
    Statusgroep varchar (1),
    Statustermijn timestamp,
    Status_E_Diensten varchar (50),
    Status_E_Loket varchar (50),
    Technisch_succes integer,
    Technisch_Cor_id integer,
    Titel varchar (200),
    Afgelost_op_onvoorw_hoofdsom integer,
    Afgelost_op_onvoorw_rente integer,
    Totaal_afgelost_op_hoofdsom integer,
    Totaal_ontvangen_rente integer,
    Totaal_bijgeschreven_rente integer,
    Direct_opeisbare_vordering integer,
    Direct_opeisbare_hoofdsom integer,
    Direct_opeisbare_rente integer,
    Totaal_gecommitteerd_bedrag integer,
    Zegge_Totaal_gecommitteerd varchar (100),
    Totaal_gedeclareerd_bedrag integer,
    Totaal_geschoonde_kosten integer,
    Totale_hoofdsom integer,
    Totaal_ingetrokken_bedrag integer,
    Kwijtsch_onvoorw_hoofdsom integer,
    Kwijtsch_onvoorw_rente integer,
    Kwijtsch_direct_opeisbaar integer,
    Kwijtsch_voorw_hoofdsom integer,
    Kwijtsch_voorw_rente integer,
    Totaal_kwijtgescholden_bedrag integer,
    Totaal_openstaand_bedrag integer,
    Direct_opeisbaar_gesteld integer,
    Totaal_uitbetaald integer,
    Totaal_verleend_bedrag integer,
    Uitlening_binnen_Fisc_eenheid varchar (1),
    Uurloon_jaar integer,
    Vaststellen_batch varchar (1),
    Vergoedingsperc integer,
    Volgnr_LB integer,
    Voorlopig_gecommitteerd integer,
    Voorlopig_gedeclareerd integer,
    Vorig_aanvraag_bedrijf_nr integer,
    Vorig_aanvraagjaar integer,
    Vorig_aanvraagnummer varchar (40),
    Vorie_aanvraagperiode integer,
    Vorig_aanvraag_volgnr integer,
    Vaststelling_conform_aanvraag varchar (1),
    VV_Aanvraagnummer varchar (12),
    Wel_akkoord_niet_verlenen varchar (1),
    Aangeboden_aan_ZER varchar (1)
);

DROP TABLE IF EXISTS DAM_DOSSIERGROEP_TCMG ;
CREATE TABLE DAM_DOSSIERGROEP_TCMG (
    Ddg_id integer,
    Age_id integer,
    Naam varchar (30),
    Toelichting varchar (2048),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Timestamp varchar (8)
);

DROP TABLE IF EXISTS DAM_LOKATIEADRES_TCMG ;
CREATE TABLE DAM_LOKATIEADRES_TCMG (
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    DLS_id integer,
    Lok_id integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    RAE_id integer,
    RAS_id integer
);

DROP TABLE IF EXISTS DAM_MDW_INTERN_HIST_TCMG ;
CREATE TABLE DAM_MDW_INTERN_HIST_TCMG (
    Dos_id integer,
    Prg_id integer,
    Mdw_id integer,
    Rol_cd varchar (3),
    Datum_van timestamp,
    Datum_tot timestamp,
    Behandelend varchar (1),
    Notitie varchar (2048),
    Mdw_id_voorheen integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30)
);

DROP TABLE IF EXISTS DAM_MDW_INTERN_TCMG ;
CREATE TABLE DAM_MDW_INTERN_TCMG (
    Behandelend varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Dos_id integer,
    Mdw_id integer,
    Mdw_id_voorheen integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Notitie varchar (2048),
    Prg_id integer,
    Rol_cd varchar (3)
);

DROP TABLE IF EXISTS DAM_STATUSHISTORIE_TCMG ;
CREATE TABLE DAM_STATUSHISTORIE_TCMG (
    Commentaar varchar (2048),
    Cor_id_tot integer,
    Cor_id_van integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Datum_tot timestamp,
    Datum_van timestamp,
    Dos_id integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Ssg_cd varchar (1),
    Sts_cd varchar (3),
    Volg_nr integer
);

DROP TABLE IF EXISTS DAM_TERMIJN_PARAAF_NOTITIE_TCMG ;
CREATE TABLE DAM_TERMIJN_PARAAF_NOTITIE_TCMG (
    Cor_id integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Dos_id integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Ter_id integer,
    Toelichting varchar (2048)
);

DROP TABLE IF EXISTS DAM_TERMIJN_TCMG ;
CREATE TABLE DAM_TERMIJN_TCMG (
    Aanvullende_voorwaarden varchar (1),
    Actie varchar (2048),
    Actie_dat timestamp,
    Con_id integer,
    Cor_id integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Dos_id integer,
    Dossiergroep_ter_id integer,
    Mdw_id varchar (12),
    Mdw_id_afgemeld integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Notitie varchar (2048),
    Opgevoerd_dat timestamp,
    Opschortend_jn varchar (1),
    Prg_id integer,
    Reactie_cd varchar (3),
    Rol_cd varchar (3),
    Ter_id integer,
    Voldaan_dat timestamp,
    Volgorde_paraaf integer
);

DROP TABLE IF EXISTS FAM_STATUSHISTORIE_TCMG ;
CREATE TABLE FAM_STATUSHISTORIE_TCMG (
    Commentaar varchar (2048),
    Datum_van timestamp,
    Datum_tot timestamp,
    Dos_id integer,
    Ssg_cd varchar (1),
    Sts_cd varchar (3),
    Tra_id integer,
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Timestamp varchar (8)
);

DROP TABLE IF EXISTS FAM_TRANSACTIE_REGEL_TCMG ;
CREATE TABLE FAM_TRANSACTIE_REGEL_TCMG (
    Tra_id integer,
    Rpt_nr integer,
    Ovk_nr varchar (20),
    Bgt_cd varchar (1),
    Rpe_datum_van timestamp,
    Vpl_tra_id integer,
    Prg_id integer,
    Vpl_volgnummer integer,
    Jaar integer,
    Reg_id integer,
    Reg_nr integer,
    Bedrag integer,
    Valutadatum timestamp,
    Iban varchar (34),
    Bic varchar (11),
    Omhang_jaar integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Timestamp varchar (8),
    Cvk_id_geselecteerd integer,
    Cvk_id_verwerkt integer,
    Volgnummer integer,
    Gecorrigeerd_jn varchar (1),
    Rpt_nr_oud varchar (20),
    Naar_oracle varchar (1),
    Boeking varchar (1),
    Imvb varchar (1)
);

DROP TABLE IF EXISTS FAM_TRANSACTIE_TCMG ;
CREATE TABLE FAM_TRANSACTIE_TCMG (
    Volgnummer integer,
    Tra_id integer,
    Prg_id integer,
    Jaar integer,
    Dos_id integer,
    Tra_cd varchar (3),
    Reden varchar (256),
    bedrag integer,
    Bedrag_nlg integer,
    Datum timestamp,
    Valutadatum timestamp,
    Fam_verplichting varchar (1),
    Fam_declaratie varchar (1),
    Fam_bij_rente varchar (1),
    Fam_kwijtschelding varchar (1),
    Fam_rest_voorschot varchar (1),
    Fam_overboeking varchar (1),
    Fam_aflossing varchar (1),
    Fam_budgetmutatie varchar (1),
    Fam_rest_aflossing varchar (1),
    Fam_betaalritme varchar (1),
    Sts_cd varchar (3),
    Ssg_cd varchar (1),
    Correctie varchar (1),
    Correctie_volgnr integer,
    Tra_id_van integer,
    Vst_id integer,
    Rel_id integer,
    Rol_cd varchar (3),
    Datum_acc_afd timestamp,
    Referentie varchar (10),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Timestamp varchar (8),
    Bedrag_ex_btw integer,
    Vst_volgnr integer,
    Duurzaam_jn varchar (1),
    Run_id integer,
    Fam_vordering varchar (1),
    Fam_vordering_afhandeling varchar (1),
    Vordering_tra_id integer,
    Storneren varchar (1),
    Vordering_bedrag integer,
    Afgelost integer,
    Kwijtgescholden integer,
    Tmp_vordering_id integer,
    Omhang_jaar integer,
    Omhang_jn varchar (1),
    Tra_id_rv integer,
    Tra_id_dcv integer,
    Jz_id integer,
    Afreken_tra_id integer,
    Correctie_bedrag_bob integer,
    Vordering_status varchar (3),
    On_hold varchar (255),
    Termijn_uitstel timestamp,
    Tra_id_ean_eap integer
);

DROP TABLE IF EXISTS FAM_VERPLICHTING_TCMG ;
CREATE TABLE FAM_VERPLICHTING_TCMG (
    Tra_id integer,
    Reg_id integer,
    Reg_nr integer,
    Verplichtingssoort varchar (1),
    Omschrijving varchar (30),
    Totaal_ingediend integer,
    Gevraagd integer,
    Totaal_geschoond integer,
    Vergoedings_pct integer,
    Intake_datum timestamp,
    Nota_datum timestamp,
    Panel_datum timestamp,
    Overige_subsidie integer,
    Timestamp varchar (8),
    Ikb_naam varchar (10),
    Inkoopbevinding varchar (30),
    Inkoopbevinding_user varchar (30),
    Betalingsverzoeknummer varchar (40)
);

DROP TABLE IF EXISTS IOM_FUNCTIE_TCMG ;
CREATE TABLE IOM_FUNCTIE_TCMG (
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Fun_cd varchar (7),
    Fun_oms varchar (50),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30)
);

DROP TABLE IF EXISTS IOM_LOCATIE_TCMG ;
CREATE TABLE IOM_LOCATIE_TCMG (
    Loc_cd varchar (2),
    Omschrijving varchar (34),
    Actief varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30)
);

DROP TABLE IF EXISTS IOM_MEDEWERKER_TCMG ;
CREATE TABLE IOM_MEDEWERKER_TCMG (
    Aanspreeknaam varchar (50),
    Achternaam varchar (25),
    Actief varchar (1),
    Banknaam varchar (50),
    Beveiligingspas varchar (1),
    Beveiligingspasnr varchar (6),
    Bic varchar (11),
    Certhoud_id integer,
    Certserienummer varchar (50),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Datum_inlog timestamp,
    Datum_uit_dienst timestamp,
    Dienstverband varchar (1),
    Eigen_vervoer_jn varchar (1),
    Fun_cd varchar (7),
    Geslacht varchar (1),
    Iban varchar (34),
    Inleen_jn varchar (1),
    Loc_cd varchar (2),
    Mdw_cd varchar (30),
    Mdw_emailadres varchar (60),
    Mdw_handtekening varchar (500),
    Mdw_handtekening_image varchar (2048),
    Mdw_id integer,
    Mobiel varchar (10),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Parkeerkaart varchar (1),
    Plaatsnaam varchar (30),
    Standplaats varchar (1),
    Telefoon varchar (10),
    Titel_na_cd varchar (4),
    Titel_voor_cd varchar (4),
    Toestel_dh varchar (5),
    Toestel_zw varchar (5),
    Tvs_cd_oud varchar (30),
    Voorletters varchar (10),
    Voornaam varchar (15),
    Voorvoegsel varchar (10)
);

DROP TABLE IF EXISTS IOM_MEDEWERKERROL_TCMG ;
CREATE TABLE IOM_MEDEWERKERROL_TCMG (
    Mdw_id integer,
    Rol_cd varchar (3),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Timestamp varchar (8),
    Actief varchar (1)
);

DROP TABLE IF EXISTS JZM_BEHANDELAAR_TCMG ;
CREATE TABLE JZM_BEHANDELAAR_TCMG (
    Mdw_id integer,
    Jz_id integer,
    Rol_cd varchar (3),
    Eigenaar varchar (1),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp
);

DROP TABLE IF EXISTS JZM_BEROEP_TCMG ;
CREATE TABLE JZM_BEROEP_TCMG (
    Jz_id integer,
    Bzr_id integer,
    Zaaknummer varchar (30),
    Datum_zitting timestamp,
    Uitspraak varchar (25),
    Datum_uitspr timestamp,
    Bedrag_schade integer,
    Bedrag_schade_nlg integer,
    Datum_schade timestamp
);

DROP TABLE IF EXISTS JZM_BEZWAAR_TCMG ;
CREATE TABLE JZM_BEZWAAR_TCMG (
    Jz_id integer,
    Belasting_cd varchar (35),
    Datum_compleet timestamp,
    Wachttijd integer,
    Datum_hoorzitting_org timestamp,
    Tijd_hoorzitting_org timestamp,
    Datum_hoorzitting timestamp,
    Tijd_hoorzitting timestamp,
    App_verschenen varchar (1),
    Datum_ontvangst timestamp,
    Datum_vragenbrief timestamp,
    Wett_termijn_7_1 timestamp,
    Wett_termijn_7_3 timestamp,
    Wett_termijn_datum timestamp,
    Uitstel_datum timestamp,
    Overschrijding_datum timestamp,
    Primair_lid_3 timestamp,
    Reken_cor_id integer,
    Reken_wett_termijn_7_1 timestamp,
    Adviescommissie varchar (1),
    Datum_1e_heropname_schade timestamp,
    Tijd_1e_heropname_schade timestamp,
    Datum_2e_heropname_schade timestamp,
    Tijd_2e_heropname_schade timestamp,
    Datum_orig_schouw timestamp,
    Tijd_orig_schouw timestamp,
    Datum_def_schouw timestamp,
    Tijd_def_schouw timestamp
);

DROP TABLE IF EXISTS JZM_BEZWAAR_TERMIJN_HIST_TCMG ;
CREATE TABLE JZM_BEZWAAR_TERMIJN_HIST_TCMG (
    Jz_id integer,
    Vanaf_datum timestamp,
    Volg_nr integer,
    Jz_nr varchar (6),
    Cor_id integer,
    Wijziging_in varchar (1),
    Sts_cd varchar (3),
    Wett_termijn_7_1 timestamp,
    Wett_termijn_7_3 timestamp,
    Uitstel_datum timestamp,
    Overschrijding_datum timestamp,
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Adviescommissie varchar (1)
);

DROP TABLE IF EXISTS JZM_BOB_WIZARD_TCMG ;
CREATE TABLE JZM_BOB_WIZARD_TCMG (
    Jz_id integer,
    Verleen_bedrag integer,
    Betaal_bedrag integer,
    Vaststelling_bedrag integer,
    Tra_cd_1 varchar (3),
    Bedrag_tra_cd_1 integer,
    Tra_cd_2 varchar (3),
    Bedrag_tra_cd_2 integer,
    Tra_cd_3 varchar (3),
    Bedrag_tra_cd_3 integer,
    Sts_cd_voor varchar (3),
    Sts_cd_na varchar (3),
    Verleend_voor integer,
    Gedeclareerd_voor integer,
    Betaald_voor integer,
    Ingetrokken_voor integer,
    Open_vordering_voor integer,
    Open_verlening_voor integer,
    Verleen_na integer,
    Gedeclareerd_na integer,
    Betaald_na integer,
    Ingetrokken_na integer,
    Open_vordering_na integer,
    Open_verlening_na integer,
    Aanmaken_bob varchar (1),
    Verwijder_trans varchar (1),
    Cst_cd varchar (8),
    Cst_cd_beschikking varchar (8),
    Cor_id_beschikking integer,
    Tra_id_beschikking_1 integer,
    Tra_cd_beschikking_1 varchar (3),
    Tra_bedrag_beschikking_1 integer,
    Tra_id_beschikking_2 integer,
    Tra_cd_beschikking_2 varchar (3),
    Tra_bedrag_beschikking_2 integer,
    Tra_id_afd integer,
    Bedrag_afspraak_afd integer,
    Datum_afspraak_afd timestamp,
    Datum_afd timestamp,
    Tra_cd_afd varchar (3),
    Vordering_tra_id_afd integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Creatie_dat timestamp,
    Creatie_user varchar (30)
);

DROP TABLE IF EXISTS JZM_BRIEF_FUNCTIE_TCMG ;
CREATE TABLE JZM_BRIEF_FUNCTIE_TCMG (
    Fnc_cd varchar (3),
    Oms varchar (64),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30)
);

DROP TABLE IF EXISTS JZM_FUNCTIE_VAN_BRIEF_TCMG ;
CREATE TABLE JZM_FUNCTIE_VAN_BRIEF_TCMG (
    Fnc_cd varchar (3),
    Cst_cd varchar (8),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30)
);

DROP TABLE IF EXISTS JZM_PROCEDURE_TCMG ;
CREATE TABLE JZM_PROCEDURE_TCMG (
    Jaar integer,
    Volgnr integer,
    Jz_nr varchar (6),
    Jz_id integer,
    Sts_cd varchar (3),
    Ssg_cd varchar (1),
    Dos_id integer,
    Cor_id integer,
    Dos_sts_cd varchar (3),
    Dos_ssg_cd varchar (1),
    Indieningsdatum timestamp,
    Datum_dos_jz timestamp,
    Actiedatum timestamp,
    Afhandeldatum timestamp,
    Notities varchar (256),
    Proc_type varchar (3),
    Jzm_bezwaar varchar (1),
    Jzm_beroep varchar (1),
    Jzm_hoger_beroep varchar (1),
    Jzm_verz_schadeverg varchar (1),
    Actuele_beh_mdw_id integer,
    Actuele_beh_rol_cd varchar (3),
    Problematiekcode integer,
    Bedrag_bob integer,
    Aard_bob varchar (1),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Technisch_cor_id integer,
    Hoofdproces varchar (10)
);

DROP TABLE IF EXISTS JZM_REACTIE_TERMIJN_TCMG ;
CREATE TABLE JZM_REACTIE_TERMIJN_TCMG (
    Rol_cd varchar (3),
    Cst_cd varchar (8),
    Reactie_cd varchar (3),
    Termijn integer,
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp
);

DROP TABLE IF EXISTS JZM_STATUSREGEL_TCMG ;
CREATE TABLE JZM_STATUSREGEL_TCMG (
    Datum_van timestamp,
    Datum_tot timestamp,
    Jz_id integer,
    Sts_cd varchar (3),
    Ssg_cd varchar (1),
    Commentaar varchar (2048),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Cor_id_van integer,
    Cor_id_tot integer,
    Volg_nr integer
);

DROP TABLE IF EXISTS JZM_UITSPRAAK_TCMG ;
CREATE TABLE JZM_UITSPRAAK_TCMG (
    Uitspraak varchar (25),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp
);

DROP TABLE IF EXISTS OBJ_LOKATIE_TCMG ;
CREATE TABLE OBJ_LOKATIE_TCMG (
    Bik_cd varchar (9),
    Bik_oms varchar (200),
    Bouwtype varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Dos_id integer,
    EobjectLocatie_id integer,
    Extra_gegevens varchar (255),
    Huisnr varchar (30),
    Huisnr_toevoeging varchar (12),
    Lok_id integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Naam varchar (100),
    Plaats varchar (30),
    Postcode varchar (6),
    Prg_id integer,
    Provincie varchar (30),
    Straat varchar (60)
);

DROP TABLE IF EXISTS PCT_MUT_TCMG ;
CREATE TABLE PCT_MUT_TCMG (
    Mutatie_srt varchar (1),
    Mutatie_ind varchar (16),
    Old_cijfer varchar (4),
    Old_letter varchar (2),
    Old_reeksindicatie varchar (1),
    Old_codebreekpunt_van varchar (5),
    Old_codebreekpunt_tm varchar (5),
    Old_woonplaatsnaam_ptt varchar (18),
    Old_woonplaatsnaam_nen varchar (24),
    Old_straatnaam_ptt varchar (17),
    Old_straatnaam_nen varchar (24),
    Old_straatnaam_off varchar (43),
    Old_extract_woonplaats varchar (4),
    Old_extract_straatnaam varchar (5),
    Old_gemeentecode varchar (4),
    Old_gemeentenaam varchar (24),
    Old_provinciecode varchar (1),
    Old_cebuco_code varchar (3),
    New_cijfer varchar (4),
    New_letter varchar (2),
    New_reeksindicatie varchar (1),
    New_codebreekpunt_van varchar (5),
    New_codebreekpunt_tm varchar (5),
    New_woonplaatsnaam_ptt varchar (18),
    New_woonplaatsnaam_nen varchar (24),
    New_straatnaam_ptt varchar (17),
    New_straatnaam_nen varchar (24),
    New_straatnaam_off varchar (43),
    New_extract_woonplaats varchar (4),
    New_extract_straatnaam varchar (5),
    New_gemeentecode varchar (4),
    New_gemeentenaam varchar (24),
    New_provinciecode varchar (2),
    New_cebuco_code varchar (3)
);

DROP TABLE IF EXISTS PCT_TCMG ;
CREATE TABLE PCT_TCMG (
    Cijfer varchar (4),
    Letter varchar (2),
    Reeksindicatie varchar (1),
    Codebreekpunt_van varchar (5),
    Codebreekpunt_tm varchar (5),
    Woonplaatsnaam_ptt varchar (18),
    Woonplaatsnaam_nen varchar (24),
    Straatnaam_ptt varchar (17),
    Straatnaam_nen varchar (24),
    Straatnaam_off varchar (43),
    Extract_woonplaats varchar (4),
    Extract_straatnaam varchar (5),
    Gemeentecode varchar (4),
    Gemeentenaam varchar (24),
    Provinciecode varchar (2),
    Cebuco_code varchar (3)
);

DROP TABLE IF EXISTS RBM_ADRES_RELATIE_TCMG ;
CREATE TABLE RBM_ADRES_RELATIE_TCMG (
    Adressoort varchar (3),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Kkr_gevalideerd varchar (1),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Rae_id integer,
    Ras_id integer,
    Rel_id integer,
    Vst_volgnr integer
);

DROP TABLE IF EXISTS RBM_ADRES_TCMG ;
CREATE TABLE RBM_ADRES_TCMG (
    Barcode varchar (25),
    Creatie_dat timestamp,
    creatie_user varchar (30),
    Huisnr integer,
    Huisnr_toe varchar (12),
    Ias_id integer,
    Landnaam varchar (60),
    Locatie_oms varchar (100),
    Mutatie_dat timestamp,
    mutatie_user varchar (30),
    Plaatsnaam varchar (80),
    Postcd varchar (12),
    Prov_cd varchar (2),
    Ras_id integer,
    Straat varchar (60),
    Validatie varchar (1)
);

DROP TABLE IF EXISTS RBM_COM_ADRES_CP_TCMG ;
CREATE TABLE RBM_COM_ADRES_CP_TCMG (
    Creatie_dat timestamp,
    creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Org_id integer,
    Per_id integer,
    Rav_id integer,
    Rca_id integer
);

DROP TABLE IF EXISTS RBM_COM_ADRES_RELATIE_TCMG ;
CREATE TABLE RBM_COM_ADRES_RELATIE_TCMG (
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Rae_id integer,
    Rca_id integer,
    Rel_id integer,
    Vst_volgnr integer
);

DROP TABLE IF EXISTS RBM_COM_ADRES_TCMG ;
CREATE TABLE RBM_COM_ADRES_TCMG (
    Com_Cd varchar (6),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Rca_id integer,
    Telnr_email varchar (60),
    Referentie varchar (10)
);

DROP TABLE IF EXISTS RBM_CONTACTPERSOON_TCMG ;
CREATE TABLE RBM_CONTACTPERSOON_TCMG (
    Afdeling varchar (60),
    Certhoud_id integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Functie varchar (30),
    Kkr_relatie_id varchar (36),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Notitie varchar (256),
    Org_id integer,
    Per_id integer,
    Ref_kkr_relatie_id varchar (36),
    Status_contactpersoon varchar (1),
    Validatie varchar (1)
);

DROP TABLE IF EXISTS RBM_CP_VESTIGING_TCMG ;
CREATE TABLE RBM_CP_VESTIGING_TCMG (
    Org_id integer,
    Per_id integer,
    Vst_volgnr integer
);

DROP TABLE IF EXISTS RBM_ORG_BSI_TCMG ;
CREATE TABLE RBM_ORG_BSI_TCMG (
    Rel_id integer,
    Bsi_cd varchar (7),
    Volg_nr integer,
    Begindatum timestamp,
    Einddatum timestamp,
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp
);

DROP TABLE IF EXISTS RBM_ORG_FAILLIET_TCMG ;
CREATE TABLE RBM_ORG_FAILLIET_TCMG (
    Kvk_nr varchar (12),
    Graydon_bedrijfsnr integer,
    Kvk_dossiernr integer,
    Kvk_kamernr integer,
    Kvk_subdossiernr integer,
    Naam varchar (132),
    Handelsnaam varchar (132),
    Straatnaam_postbus varchar (50),
    Huisnr_postbusnr integer,
    Huisnr_toevoeging varchar (12),
    Postcode varchar (12),
    Woonplaats varchar (30),
    Land varchar (30),
    Actuele_faillisement_cd varchar (4),
    Actuele_status varchar (10),
    Actuele_opheffings_cd varchar (2)
);

DROP TABLE IF EXISTS RBM_ORG_JAAR_TCMG ;
CREATE TABLE RBM_ORG_JAAR_TCMG (
    Rel_id integer,
    Jaar integer,
    Aantal_werknemers integer,
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Timestamp varchar (8),
    Omzet integer,
    Loonsom integer,
    So_loonsom integer,
    Max_so_vermindering integer,
    Peildatum timestamp,
    Aantal_so_werknemers integer,
    Bron varchar (12),
    Senterniveau_jn varchar (1),
    Lb_verm_voorlopig integer,
    Lb_vermindering_eindafrekening integer,
    Balanstotaal integer
);

DROP TABLE IF EXISTS RBM_ORG_NAAM_TCMG ;
CREATE TABLE RBM_ORG_NAAM_TCMG (
    Org_id integer,
    Org_naam varchar (625),
    Org_naam_type varchar (1),
    Sushi_foutmelding varchar (200),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Kkr_gevalideerd varchar (1)
);

DROP TABLE IF EXISTS RBM_ORG_TCMG ;
CREATE TABLE RBM_ORG_TCMG (
    Bik_Cd varchar (9),
    Bron_jr varchar (1),
    BTW_nummer varchar (30),
    BTW_plichtig varchar (3),
    IB_plichtig_sinds timestamp,
    Jaar_oprichting integer,
    Kkr_RSIN_afwijkend varchar (1),
    KVK_nr varchar (12),
    Naam varchar (625),
    Notitie varchar (256),
    Rel_id integer,
    Rvm_cd varchar (5),
    Status_org varchar (1),
    Volg_nr_LB integer,
    Voortzetting_van_rel_id varchar (12),
    VPB_IB_nummer varchar (35),
    IB_VPB_Plichtig varchar (1)
);

DROP TABLE IF EXISTS RBM_PERSOON_TCMG ;
CREATE TABLE RBM_PERSOON_TCMG (
    Aanhef varchar (10),
    Aanlevernaam varchar (625),
    Aanspreeknaam varchar (625),
    Achternaam varchar (414),
    Foutmelding varchar (100),
    Geboortedatum timestamp,
    Geslacht varchar (1),
    Import_contactpersonen_id integer,
    Notitie varchar (256),
    Rbm_persoon_contact varchar (1),
    Rbm_persoon_particulier varchar (1),
    Rel_id integer,
    Status_persoon varchar (1),
    Sushi_foutmelding varchar (200),
    Taal varchar (2),
    Titels_na varchar (50),
    Titels_voor varchar (50),
    Tussenvoegsels varchar (10),
    Validatie varchar (1),
    Voorletters varchar (6),
    Voornaam varchar (200),
    XML_String varchar (2048)
);

DROP TABLE IF EXISTS RBM_REKENINGNRS_TCMG ;
CREATE TABLE RBM_REKENINGNRS_TCMG (
    Banknaam varchar (50),
    Bic varchar (11),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Externe_bron_cd varchar (10),
    Goedkeuring_sts varchar (1),
    Iban varchar (34),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Rel_id integer,
    User_akkoord varchar (30)
);

DROP TABLE IF EXISTS RBM_REKNR_MUT_TCMG ;
CREATE TABLE RBM_REKNR_MUT_TCMG (
    Rel_id integer,
    Volgnummer integer,
    Org_banknaam varchar (30),
    Org_bankgironr varchar (11),
    New_banknaam varchar (30),
    New_bankgironr varchar (11),
    Gebruiker varchar (30),
    Datum_mutatie timestamp,
    Iban varchar (34),
    New_iban varchar (34),
    Bic varchar (11),
    New_bic varchar (11),
    Org_user_akkoord varchar (30),
    New_user_akkoord varchar (30),
    Org_goedkeuring_sts varchar (1),
    New_goedkeuring_sts varchar (1),
    Externe_bron_cd varchar (10)
);

DROP TABLE IF EXISTS RBM_RELATIE_TCMG ;
CREATE TABLE RBM_RELATIE_TCMG (
    Actief varchar (1),
    Auth_id integer,
    Belastingeenheid integer,
    Creatie_dat timestamp,
    creatie_user varchar (30),
    Fiscaalnr varchar (10),
    IdE_id integer,
    Invoer_id integer,
    KR_Gevalideerd varchar (1),
    Kkr_Relatie_id varchar (10),
    Mutatie_dat timestamp,
    mutatie_user varchar (30),
    Rbm_org varchar (1),
    Rbm_persoon varchar (1),
    Ref_kkr_relatie_id varchar (10),
    Rel_id integer,
    Relatietype varchar (1)
);

DROP TABLE IF EXISTS RBM_SBI_ORG_TCMG ;
CREATE TABLE RBM_SBI_ORG_TCMG (
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Hoofdactiviteit varchar (1),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Rel_id integer,
    Sbi_cd integer
);

DROP TABLE IF EXISTS RBM_VESTIGING_TCMG ;
CREATE TABLE RBM_VESTIGING_TCMG (
    Actief varchar (1),
    Auth_id integer,
    Bik_cd varchar (9),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Hoofd_neven varchar (1),
    Kkr_conversie varchar (1),
    Kkr_gevalideerd varchar (1),
    Kkr_gevonden varchar (1),
    Kkr_relatie_id varchar (36),
    Kkr_verversingsdatum timestamp,
    KvK_volgnr varchar (4),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Ref_Kkr_relatie_id varchar (36),
    Rel_id integer,
    Vest_naam varchar (625),
    Vestigings_nummer varchar (12),
    Vst_volgnr integer
);

DROP TABLE IF EXISTS RDM_BUDGETONDERVERDELING_TCMG ;
CREATE TABLE RDM_BUDGETONDERVERDELING_TCMG (
    Bgt_cd varchar (1),
    Budget integer,
    Budget_uitputting integer,
    Correctie_budget integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Jaar integer,
    Koppelen_jn varchar (1),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Ovk_nr varchar (20),
    Reg_id integer,
    Rpe_datum_van timestamp,
    Rpt_nr integer,
    Verdeeld_budget integer,
    Vrij_budget integer
);

DROP TABLE IF EXISTS RDM_CLASSIFICATIE_TCMG ;
CREATE TABLE RDM_CLASSIFICATIE_TCMG (
    Prg_id integer,
    Class_cd varchar (10),
    Class_oms varchar (100),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp
);

DROP TABLE IF EXISTS RDM_JAARBUDGET_TCMG ;
CREATE TABLE RDM_JAARBUDGET_TCMG (
    Afgesloten varchar (1),
    Bgt_cd varchar (1),
    Budget_uitputting integer,
    Correctie_budget integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Datum_van timestamp,
    Jaar integer,
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Ovk_nr varchar (20),
    Rpt_nr integer,
    Tot_budget integer,
    Verdeeld_budget integer,
    Verdeeld_jn varchar (1),
    Vrij_budget integer
);

DROP TABLE IF EXISTS RDM_MANDAAT_TCMG ;
CREATE TABLE RDM_MANDAAT_TCMG (
    Mdt_id integer,
    Middelen_type varchar (2),
    Mandaat_srt varchar (2),
    Max_bedrag integer,
    Rdm_mandaat_rol varchar (1),
    Rdm_mandaat_mdw varchar (1),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Mdw_id integer,
    Reg_id integer,
    Rol_cd varchar (3)
);

DROP TABLE IF EXISTS RDM_OVEREENKOMST_DOCUMENT_TCMG ;
CREATE TABLE RDM_OVEREENKOMST_DOCUMENT_TCMG (
    Ovk_nr varchar (20),
    Doc_naam varchar (255),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Bgt_cd varchar (1),
    Rpt_nr integer,
    Datum_van timestamp
);

DROP TABLE IF EXISTS RDM_PERIODE_TCMG ;
CREATE TABLE RDM_PERIODE_TCMG (
    Ovk_nr varchar (20),
    Rpt_nr integer,
    Bgt_cd varchar (1),
    Datum_van timestamp,
    Datum_tot timestamp,
    Kopieer_periode varchar (1),
    Auto_sap_jn varchar (1),
    Comm_rente_pct integer,
    Beschik_datum timestamp,
    Tot_budget integer,
    Verdeeld_budget integer,
    Omschrijving varchar (60),
    Prg_cd varchar (12),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Timestamp varchar (8),
    Bdg_verdelen_100_pct_dp varchar (1),
    Bdg_verdelen_100_pct_th varchar (1),
    Iban varchar (34),
    Bic varchar (11),
    Imvb integer,
    Correctie_code varchar (5),
    Auto_oracle varchar (1),
    Boeking varchar (1),
    Fin_soort varchar (1),
    Kenmerk_lijn varchar (20),
    Aflossing integer
);

DROP TABLE IF EXISTS RDM_PRG_OVEREENKOMST_TCMG ;
CREATE TABLE RDM_PRG_OVEREENKOMST_TCMG (
    Prg_id integer,
    Ovk_nr varchar (20),
    Datum_van timestamp,
    Datum_tot timestamp,
    Inhoud varchar (2048),
    Status varchar (1),
    Contractdatum timestamp,
    Totaal_budget integer,
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Mjp_jn varchar (1),
    Ovk_budget_controle varchar (1),
    Vrij_budget integer,
    Budget_uitputting integer
);

DROP TABLE IF EXISTS RDM_PROGRAMMAMEDEWERKERROL_TCMG ;
CREATE TABLE RDM_PROGRAMMAMEDEWERKERROL_TCMG (
    Prg_id integer,
    Mdw_id integer,
    Auth_mdw_cd varchar (30),
    Rol_cd varchar (3),
    Actief varchar (1),
    Opmerking varchar (255),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Timestamp varchar (8),
    Senioriteit varchar (30),
    Mentor_id integer,
    Vervang_id integer,
    Vervang_rol varchar (3),
    Acc_id integer,
    Mdw_id_parf_naar integer,
    Mentor_rol_cd varchar (3)
);

DROP TABLE IF EXISTS RDM_REGELING_TCMG ;
CREATE TABLE RDM_REGELING_TCMG (
    Reg_id integer,
    Reg_cd varchar (20),
    Reg_oms varchar (120),
    Prg_id integer,
    Thema varchar (1),
    Rap_freq integer,
    Ingangs_datum timestamp,
    Pub_datum timestamp,
    Eind_datum timestamp,
    Reg_document varchar (50),
    Betaalmodule varchar (1),
    Regelingscontrole varchar (1),
    Ic_helptekst varchar (2048),
    Geblokkeerd_jn varchar (1),
    Min_id integer,
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Reg_prefix varchar (6),
    Volg_nr integer,
    Mail_bericht_parafering varchar (1),
    Reg_mail_adres varchar (60),
    Reg_geen_dig_parafering varchar (1),
    Fin_schermen varchar (1),
    Budgetbewaking_pct integer,
    Budgetbewaking_hard varchar (1),
    Dig_parf_mand varchar (1),
    Cst_set_cd varchar (10),
    Auto_samenvoeg_jn varchar (1),
    Fpc_status varchar (1),
    Dcp_automatisch_jn varchar (1),
    Paraf_mandat_pr_rol_jn varchar (1),
    Dos_referentie_jaar varchar (4),
    Auto_insert_sde_jn varchar (1),
    Ingangsdatum_zer timestamp
);

DROP TABLE IF EXISTS RDM_REGPAR_BUDGONDVERD_TCMG ;
CREATE TABLE RDM_REGPAR_BUDGONDVERD_TCMG (
    Ovk_nr varchar (20),
    Rpt_nr integer,
    Bgt_cd varchar (1),
    Rpe_datum_van timestamp,
    Jaar integer,
    Reg_id integer,
    Reg_nr integer,
    Budget integer,
    Budget_uitputting integer,
    Koppelen_jn varchar (1),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    Correctie_budget integer,
    Vrij_budget integer,
    Rpt_nr_oud varchar (20)
);

DROP TABLE IF EXISTS RDM_STATUSOVERG_BIJ_BRIEF_TCMG ;
CREATE TABLE RDM_STATUSOVERG_BIJ_BRIEF_TCMG (
    Reg_id integer,
    Status_van varchar (3),
    Statusgroep varchar (1),
    Status_naar varchar (3),
    Cst_cd varchar (8),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Xps_cd varchar (10)
);

DROP TABLE IF EXISTS RDM_VARIABELE_TCMG ;
CREATE TABLE RDM_VARIABELE_TCMG (
    Reg_id integer,
    Code varchar (50),
    Begindatum timestamp,
    Inhoud varchar (255),
    Toelichting varchar (2048),
    Einddatum timestamp,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30)
);

DROP TABLE IF EXISTS STM_BSI_TCMG ;
CREATE TABLE STM_BSI_TCMG (
    Startdatum timestamp,
    Einddatum timestamp,
    Bsi_cd varchar (7),
    Bsi_oms varchar (100),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp
);

DROP TABLE IF EXISTS STM_REACTIE_TCMG ;
CREATE TABLE STM_REACTIE_TCMG (
    Reactie_cd varchar (3),
    Reactie_oms varchar (60),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp
);

DROP TABLE IF EXISTS STM_ROL_TCMG ;
CREATE TABLE STM_ROL_TCMG (
    Rol_cd varchar (3),
    Rol_oms varchar (50),
    Interne_rol varchar (1),
    Externe_rol varchar (1),
    Organisatie_rol varchar (1),
    Controller varchar (1),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Type_rol varchar (30),
    Ed_rol_cd integer,
    Ed_rol_oms varchar (50)
);

DROP TABLE IF EXISTS STM_SBI_TCMG ;
CREATE TABLE STM_SBI_TCMG (
    Sbi_cd integer,
    Sbi_oms varchar (500),
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30)
);

DROP TABLE IF EXISTS STM_STATUS_TCMG ;
CREATE TABLE STM_STATUS_TCMG (
    Sts_cd varchar (3),
    Sts_oms varchar (50),
    Ssg_cd varchar (1),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp,
    Sts_e_indienen varchar (50),
    Eindstatus varchar (1),
    Sts_e_loket varchar (50)
);

DROP TABLE IF EXISTS STM_STATUSOVERG_BIJ_BRIEF_TCMG ;
CREATE TABLE STM_STATUSOVERG_BIJ_BRIEF_TCMG (
    Van_status varchar (3),
    Naar_status varchar (3),
    Ssg_cd varchar (1),
    Cst_cd varchar (8),
    Creatie_user varchar (30),
    Creatie_dat timestamp,
    Mutatie_user varchar (30),
    Mutatie_dat timestamp
);

DROP TABLE IF EXISTS VKM_TOEGEV_VAR_VELD_WAARDE_TCMG ;
CREATE TABLE VKM_TOEGEV_VAR_VELD_WAARDE_TCMG (
    Vkt_id integer,
    Fysieke_naam varchar (30),
    Waarde varchar (60),
    Volgorde integer
);

DROP TABLE IF EXISTS VKM_TOEGEVOEGD_VAR_VELD_TCMG ;
CREATE TABLE VKM_TOEGEVOEGD_VAR_VELD_TCMG (
    Vkt_id integer,
    Fysieke_naam varchar (30),
    Datum_start timestamp,
    Datum_einde timestamp,
    Volgorde integer,
    Verplicht_jn varchar (1),
    Prompt varchar (40),
    Min_waarde integer,
    Max_waarde integer,
    Default_waarde varchar (40),
    Helptekst varchar (72)
);

DROP TABLE IF EXISTS VKM_VAR_GEGEVENS_TCMG ;
CREATE TABLE VKM_VAR_GEGEVENS_TCMG (
    BEDRAG_01 integer,
    BEDRAG_02 integer,
    BEDRAG_03 integer,
    BEDRAG_04 integer,
    BEDRAG_05 integer,
    BEDRAG_06 integer,
    BEDRAG_07 integer,
    BEDRAG_08 integer,
    BEDRAG_09 integer,
    BEDRAG_10 integer,
    BEDRAG_11 integer,
    BEDRAG_12 integer,
    BEDRAG_13 integer,
    BEDRAG_14 integer,
    BEDRAG_15 integer,
    BEDRAG_16 integer,
    BEDRAG_17 integer,
    BEDRAG_18 integer,
    BEDRAG_19 integer,
    BEDRAG_20 integer,
    BEDRAG_21 integer,
    BEDRAG_22 integer,
    BEDRAG_23 integer,
    BEDRAG_24 integer,
    BEDRAG_25 integer,
    BEDRAG_26 integer,
    BEDRAG_27 integer,
    BEDRAG_28 integer,
    BEDRAG_29 integer,
    BEDRAG_30 integer,
    BEDRAG_31 integer,
    BEDRAG_32 integer,
    BEDRAG_33 integer,
    BEDRAG_34 integer,
    BEDRAG_35 integer,
    BEDRAG_36 integer,
    BEDRAG_37 integer,
    BEDRAG_38 integer,
    BEDRAG_39 integer,
    BEDRAG_40 integer,
    Creatie_dat timestamp,
    Creatie_user varchar (30),
    DATUM_01 timestamp,
    DATUM_02 timestamp,
    DATUM_03 timestamp,
    DATUM_04 timestamp,
    DATUM_05 timestamp,
    DATUM_06 timestamp,
    DATUM_07 timestamp,
    DATUM_08 timestamp,
    DATUM_09 timestamp,
    DATUM_10 timestamp,
    DATUM_11 timestamp,
    DATUM_12 timestamp,
    DATUM_13 timestamp,
    DATUM_14 timestamp,
    DATUM_15 timestamp,
    DATUM_16 timestamp,
    DATUM_17 timestamp,
    DATUM_18 timestamp,
    DATUM_19 timestamp,
    DATUM_20 timestamp,
    DATUM_AANMAAK timestamp,
    DROPDOWNLIST_01 varchar (60),
    DROPDOWNLIST_02 varchar (60),
    DROPDOWNLIST_03 varchar (60),
    DROPDOWNLIST_04 varchar (60),
    DROPDOWNLIST_05 varchar (60),
    DROPDOWNLIST_06 varchar (60),
    DROPDOWNLIST_07 varchar (60),
    DROPDOWNLIST_08 varchar (60),
    DROPDOWNLIST_09 varchar (60),
    DROPDOWNLIST_10 varchar (60),
    DROPDOWNLIST_11 varchar (60),
    DROPDOWNLIST_12 varchar (60),
    DROPDOWNLIST_13 varchar (60),
    DROPDOWNLIST_14 varchar (60),
    DROPDOWNLIST_15 varchar (60),
    DROPDOWNLIST_16 varchar (60),
    DROPDOWNLIST_17 varchar (60),
    DROPDOWNLIST_18 varchar (60),
    DROPDOWNLIST_19 varchar (60),
    DROPDOWNLIST_20 varchar (60),
    DROPDOWNLIST_21 varchar (60),
    DROPDOWNLIST_22 varchar (60),
    DROPDOWNLIST_23 varchar (60),
    DROPDOWNLIST_24 varchar (60),
    DROPDOWNLIST_25 varchar (60),
    DROPDOWNLIST_26 varchar (60),
    DROPDOWNLIST_27 varchar (60),
    DROPDOWNLIST_28 varchar (60),
    DROPDOWNLIST_29 varchar (60),
    DROPDOWNLIST_30 varchar (60),
    DROPDOWNLIST_31 varchar (60),
    DROPDOWNLIST_32 varchar (60),
    DROPDOWNLIST_33 varchar (60),
    DROPDOWNLIST_34 varchar (60),
    DROPDOWNLIST_35 varchar (60),
    DROPDOWNLIST_36 varchar (60),
    DROPDOWNLIST_37 varchar (60),
    DROPDOWNLIST_38 varchar (60),
    DROPDOWNLIST_39 varchar (60),
    DROPDOWNLIST_40 varchar (60),
    INT_01 integer,
    INT_02 integer,
    INT_03 integer,
    INT_04 integer,
    INT_05 integer,
    INT_06 integer,
    INT_07 integer,
    INT_08 integer,
    INT_09 integer,
    INT_10 integer,
    INT_11 integer,
    INT_12 integer,
    INT_13 integer,
    INT_14 integer,
    INT_15 integer,
    INT_16 integer,
    INT_17 integer,
    INT_18 integer,
    INT_19 integer,
    INT_20 integer,
    INT_21 integer,
    INT_22 integer,
    INT_23 integer,
    INT_24 integer,
    INT_25 integer,
    INT_26 integer,
    INT_27 integer,
    INT_28 integer,
    INT_29 integer,
    INT_30 integer,
    INT_31 integer,
    INT_32 integer,
    INT_33 integer,
    INT_34 integer,
    INT_35 integer,
    INT_36 integer,
    INT_37 integer,
    INT_38 integer,
    INT_39 integer,
    INT_40 integer,
    JA_NEE_01 varchar (1),
    JA_NEE_02 varchar (1),
    JA_NEE_03 varchar (1),
    JA_NEE_04 varchar (1),
    JA_NEE_05 varchar (1),
    JA_NEE_06 varchar (1),
    JA_NEE_07 varchar (1),
    JA_NEE_08 varchar (1),
    JA_NEE_09 varchar (1),
    JA_NEE_10 varchar (1),
    JA_NEE_11 varchar (1),
    JA_NEE_12 varchar (1),
    JA_NEE_13 varchar (1),
    JA_NEE_14 varchar (1),
    JA_NEE_15 varchar (1),
    JA_NEE_16 varchar (1),
    JA_NEE_17 varchar (1),
    JA_NEE_18 varchar (1),
    JA_NEE_19 varchar (1),
    JA_NEE_20 varchar (1),
    JA_NEE_21 varchar (1),
    JA_NEE_22 varchar (1),
    JA_NEE_23 varchar (1),
    JA_NEE_24 varchar (1),
    JA_NEE_25 varchar (1),
    JA_NEE_26 varchar (1),
    JA_NEE_27 varchar (1),
    JA_NEE_28 varchar (1),
    JA_NEE_29 varchar (1),
    JA_NEE_30 varchar (1),
    JA_NEE_NVT_01 varchar (1),
    JA_NEE_NVT_02 varchar (1),
    JA_NEE_NVT_03 varchar (1),
    JA_NEE_NVT_04 varchar (1),
    JA_NEE_NVT_05 varchar (1),
    JA_NEE_NVT_06 varchar (1),
    JA_NEE_NVT_07 varchar (1),
    JA_NEE_NVT_08 varchar (1),
    JA_NEE_NVT_09 varchar (1),
    JA_NEE_NVT_10 varchar (1),
    JA_NEE_NVT_11 varchar (1),
    JA_NEE_NVT_12 varchar (1),
    JA_NEE_NVT_13 varchar (1),
    JA_NEE_NVT_14 varchar (1),
    JA_NEE_NVT_15 varchar (1),
    JA_NEE_NVT_16 varchar (1),
    JA_NEE_NVT_17 varchar (1),
    JA_NEE_NVT_18 varchar (1),
    JA_NEE_NVT_19 varchar (1),
    JA_NEE_NVT_20 varchar (1),
    JA_NEE_ONB_01 varchar (1),
    JA_NEE_ONB_02 varchar (1),
    JA_NEE_ONB_03 varchar (1),
    JA_NEE_ONB_04 varchar (1),
    JA_NEE_ONB_05 varchar (1),
    JA_NEE_ONB_06 varchar (1),
    JA_NEE_ONB_07 varchar (1),
    JA_NEE_ONB_08 varchar (1),
    JA_NEE_ONB_09 varchar (1),
    JA_NEE_ONB_10 varchar (1),
    JA_NEE_ONB_11 varchar (1),
    JA_NEE_ONB_12 varchar (1),
    JA_NEE_ONB_13 varchar (1),
    JA_NEE_ONB_14 varchar (1),
    JA_NEE_ONB_15 varchar (1),
    JA_NEE_ONB_16 varchar (1),
    JA_NEE_ONB_17 varchar (1),
    JA_NEE_ONB_18 varchar (1),
    JA_NEE_ONB_19 varchar (1),
    JA_NEE_ONB_20 varchar (1),
    Mutatie_dat timestamp,
    Mutatie_user varchar (30),
    NUMERIEK_01 integer,
    NUMERIEK_02 integer,
    NUMERIEK_03 integer,
    NUMERIEK_04 integer,
    NUMERIEK_05 integer,
    NUMERIEK_06 integer,
    NUMERIEK_07 integer,
    NUMERIEK_08 integer,
    NUMERIEK_09 integer,
    NUMERIEK_10 integer,
    NUMERIEK_11 integer,
    NUMERIEK_12 integer,
    NUMERIEK_13 integer,
    NUMERIEK_14 integer,
    NUMERIEK_15 integer,
    NUMERIEK_16 integer,
    NUMERIEK_17 integer,
    NUMERIEK_18 integer,
    NUMERIEK_19 integer,
    NUMERIEK_20 integer,
    NUMERIEK_21 integer,
    NUMERIEK_22 integer,
    NUMERIEK_23 integer,
    NUMERIEK_24 integer,
    NUMERIEK_25 integer,
    NUMERIEK_26 integer,
    NUMERIEK_27 integer,
    NUMERIEK_28 integer,
    NUMERIEK_29 integer,
    NUMERIEK_30 integer,
    NUMERIEK_31 integer,
    NUMERIEK_32 integer,
    NUMERIEK_33 integer,
    NUMERIEK_34 integer,
    NUMERIEK_35 integer,
    NUMERIEK_36 integer,
    NUMERIEK_37 integer,
    NUMERIEK_38 integer,
    NUMERIEK_39 integer,
    NUMERIEK_40 integer,
    OPTIONBUTTON_01 varchar (60),
    OPTIONBUTTON_02 varchar (60),
    OPTIONBUTTON_03 varchar (60),
    OPTIONBUTTON_04 varchar (60),
    OPTIONBUTTON_05 varchar (60),
    OPTIONBUTTON_06 varchar (60),
    OPTIONBUTTON_07 varchar (60),
    OPTIONBUTTON_08 varchar (60),
    OPTIONBUTTON_09 varchar (60),
    OPTIONBUTTON_10 varchar (60),
    OPTIONBUTTON_11 varchar (60),
    OPTIONBUTTON_12 varchar (60),
    OPTIONBUTTON_13 varchar (60),
    OPTIONBUTTON_14 varchar (60),
    OPTIONBUTTON_15 varchar (60),
    OPTIONBUTTON_16 varchar (60),
    OPTIONBUTTON_17 varchar (60),
    OPTIONBUTTON_18 varchar (60),
    OPTIONBUTTON_19 varchar (60),
    OPTIONBUTTON_20 varchar (60),
    TEKSTBLOK_01 varchar (2048),
    TEKSTBLOK_02 varchar (2048),
    TEKSTBLOK_03 varchar (2048),
    TEKSTBLOK_04 varchar (2048),
    TEKSTBLOK_05 varchar (2048),
    TEKSTBLOK_06 varchar (2048),
    TEKSTBLOK_07 varchar (2048),
    TEKSTBLOK_08 varchar (2048),
    TEKSTBLOK_09 varchar (2048),
    TEKSTBLOK_10 varchar (2048),
    VARCHAR_60_01 varchar (60),
    VARCHAR_60_02 varchar (60),
    VARCHAR_60_03 varchar (60),
    VARCHAR_60_04 varchar (60),
    VARCHAR_60_05 varchar (60),
    VARCHAR_60_06 varchar (60),
    VARCHAR_60_07 varchar (60),
    VARCHAR_60_08 varchar (60),
    VARCHAR_60_09 varchar (60),
    VARCHAR_60_10 varchar (60),
    VARCHAR_60_11 varchar (60),
    VARCHAR_60_12 varchar (60),
    VARCHAR_60_13 varchar (60),
    VARCHAR_60_14 varchar (60),
    VARCHAR_60_15 varchar (60),
    VARCHAR_60_16 varchar (60),
    VARCHAR_60_17 varchar (60),
    VARCHAR_60_18 varchar (60),
    VARCHAR_60_19 varchar (60),
    VARCHAR_60_20 varchar (60),
    VARCHAR_60_21 varchar (60),
    VARCHAR_60_22 varchar (60),
    VARCHAR_60_23 varchar (60),
    VARCHAR_60_24 varchar (60),
    VARCHAR_60_25 varchar (60),
    VARCHAR_60_26 varchar (60),
    VARCHAR_60_27 varchar (60),
    VARCHAR_60_28 varchar (60),
    VARCHAR_60_29 varchar (60),
    VARCHAR_60_30 varchar (60),
    VARCHAR_60_31 varchar (60),
    VARCHAR_60_32 varchar (60),
    VARCHAR_60_33 varchar (60),
    VARCHAR_60_34 varchar (60),
    VARCHAR_60_35 varchar (60),
    VARCHAR_60_36 varchar (60),
    VARCHAR_60_37 varchar (60),
    VARCHAR_60_38 varchar (60),
    VARCHAR_60_39 varchar (60),
    VARCHAR_60_40 varchar (60),
    VGS_ID integer,
    VVG_VKM_VAR_GEGEVENS_DOS varchar (1),
    VVG_VKM_VAR_GEGEVENS_PRG varchar (1),
    VVG_VKT_ID integer,
    VVG_DOS_ID integer
);

DROP TABLE IF EXISTS VKM_VAR_KAART_TCMG ;
CREATE TABLE VKM_VAR_KAART_TCMG (
    Vkt_id integer,
    Kaart_naam varchar (30),
    Datum_start timestamp,
    Datum_einde timestamp,
    Omschrijving varchar (2000),
    Vkm_var_kaart_dos varchar (1),
    Vkm_var_kaart_prg varchar (1),
    Prg_id integer,
    Reg_id integer,
    Reg_id_regpar integer,
    Reg_Nr integer,
    Vkm_var_kaart_dos_prg varchar (1),
    Vkm_var_kaart_dos_reg varchar (1),
    Vkm_var_kaart_dos_regpar varchar (1),
    Geblokkeerd varchar (1),
    Copy_jn varchar (1)
);

