name:                csv2tables
version:             0.1.0.0
github:              hanjoosten/csv2tables
license:             BSD3
author:              Han Joosten
maintainer:          han.joosten.han@gmail.com
copyright:           Han Joosten

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hanjoosten/csv2tables#readme>

dependencies:
- base >= 4.11 && < 10
- Cabal >= 3.0.1
- csv >= 0.1
- hspec
- lens >= 4.18
- rio >= 0.1.15.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - xlsx

executables:
  csv2tables:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - csv2tables
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  csv2tables-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - csv2tables
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
